{% set version = '3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bsvars
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bsvars_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bsvars/bsvars_{{ version }}.tar.gz
  sha256: 875614c640a245c852a2fd8558618e2818b4487989a3cb6f83bf376f48076842

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ stdlib('c') }}  # [not win]
    - {{ stdlib('m2w64_c') }}  # [win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-gigrvg
    - r-r6
    - r-rcpp >=1.0.7
    - r-rcpparmadillo
    - r-rcppprogress >=0.1
    - r-rcpptn
    - r-stochvol
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs           # [win]
    - {{ native }}libwinpthread-git  # [win]
    - r-gigrvg
    - r-r6
    - r-rcpp >=1.0.7
    - r-rcpparmadillo
    - r-rcppprogress >=0.1
    - r-rcpptn
    - r-stochvol

test:
  commands:
    - $R -e "library('bsvars')"           # [not win]
    - "\"%R%\" -e \"library('bsvars')\""  # [win]

about:
  home: https://bsvars.github.io/bsvars/
  dev_url: https://github.com/bsvars/bsvars/
  license: GPL-3.0-or-later
  summary: "Provides fast and efficient procedures for Bayesian analysis of Structural Vector
    Autoregressions. This package estimates a wide range of models, including homo-,
    heteroskedastic, and non-normal specifications. Structural models can be identified
    by adjustable exclusion restrictions, time-varying volatility, or non-normality.
    They all include a flexible three-level equation-specific local-global hierarchical
    prior distribution for the estimated level of shrinkage for autoregressive and structural
    parameters. Additionally, the package facilitates predictive and structural analyses
    such as impulse responses, forecast error variance and historical decompositions,
    forecasting, verification of heteroskedasticity, non-normality, and hypotheses on
    autoregressive parameters, as well as analyses of structural shocks, volatilities,
    and fitted values. Beautiful plots, informative summary functions, and extensive
    documentation complement all this. The implemented techniques align closely with
    those presented in L\xFCtkepohl, Shang, Uzeda, & Wo\u017Aniak (2024) <doi:10.48550/arXiv.2404.11057>,
    L\xFCtkepohl & Wo\u017Aniak (2020) <doi:10.1016/j.jedc.2020.103862>, and Song &
    Wo\u017Aniak (2021) <doi:10.1093/acrefore/9780190625979.013.174>."
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: bsvars
# Type: Package
# Title: Bayesian Estimation of Structural Vector Autoregressive Models
# Description: Provides fast and efficient procedures for Bayesian analysis of Structural Vector Autoregressions. This package estimates a wide range of models, including homo-, heteroskedastic, and non-normal specifications. Structural models can be identified by adjustable exclusion restrictions, time-varying volatility, or non-normality. They all include a flexible three-level equation-specific local-global hierarchical prior distribution for the estimated level of shrinkage for autoregressive and structural parameters. Additionally, the package facilitates predictive and structural analyses such as impulse responses, forecast error variance and historical decompositions, forecasting, verification of heteroskedasticity, non-normality, and hypotheses on autoregressive parameters, as well as analyses of structural shocks, volatilities, and fitted values. Beautiful plots, informative summary functions, and extensive documentation complement all this. The implemented techniques align closely with those presented in Lutkepohl, Shang, Uzeda, & Wozniak (2024) <doi:10.48550/arXiv.2404.11057>, Lutkepohl & Wozniak (2020) <doi:10.1016/j.jedc.2020.103862>, and Song & Wozniak (2021) <doi:10.1093/acrefore/9780190625979.013.174>.
# Version: 3.0
# Date: 2024-06-15
# Authors@R: person("Tomasz", "Wozniak", , "wozniak.tom@pm.me", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-2212-2378"))
# Maintainer: Tomasz Wozniak <wozniak.tom@pm.me>
# Imports: Rcpp (>= 1.0.7), RcppProgress (>= 0.1), RcppTN, GIGrvg, R6, stochvol
# Suggests: tinytest
# LinkingTo: Rcpp, RcppProgress, RcppArmadillo, RcppTN
# License: GPL (>= 3)
# URL: https://bsvars.github.io/bsvars/
# BugReports: https://github.com/bsvars/bsvars/issues
# Encoding: UTF-8
# RoxygenNote: 7.3.1
# NeedsCompilation: yes
# Packaged: 2024-06-16 23:24:52 UTC; twozniak
# Author: Tomasz Wozniak [aut, cre] (<https://orcid.org/0000-0003-2212-2378>)
# Depends: R (>= 3.5.0)
# Repository: CRAN
# Date/Publication: 2024-06-19 09:10:05 UTC
